# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _dap
else:
    import _dap

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dap.delete_SwigPyIterator

    def value(self):
        return _dap.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _dap.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _dap.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _dap.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _dap.SwigPyIterator_equal(self, x)

    def copy(self):
        return _dap.SwigPyIterator_copy(self)

    def next(self):
        return _dap.SwigPyIterator_next(self)

    def __next__(self):
        return _dap.SwigPyIterator___next__(self)

    def previous(self):
        return _dap.SwigPyIterator_previous(self)

    def advance(self, n):
        return _dap.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _dap.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _dap.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _dap.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _dap.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _dap.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _dap.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _dap:
_dap.SwigPyIterator_swigregister(SwigPyIterator)
class SizeTPtr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _dap.SizeTPtr_swiginit(self, _dap.new_SizeTPtr())
    __swig_destroy__ = _dap.delete_SizeTPtr

    def assign(self, value):
        return _dap.SizeTPtr_assign(self, value)

    def value(self):
        return _dap.SizeTPtr_value(self)

    def cast(self):
        return _dap.SizeTPtr_cast(self)

    @staticmethod
    def frompointer(t):
        return _dap.SizeTPtr_frompointer(t)

# Register SizeTPtr in _dap:
_dap.SizeTPtr_swigregister(SizeTPtr)
class UInt8Ptr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _dap.UInt8Ptr_swiginit(self, _dap.new_UInt8Ptr())
    __swig_destroy__ = _dap.delete_UInt8Ptr

    def assign(self, value):
        return _dap.UInt8Ptr_assign(self, value)

    def value(self):
        return _dap.UInt8Ptr_value(self)

    def cast(self):
        return _dap.UInt8Ptr_cast(self)

    @staticmethod
    def frompointer(t):
        return _dap.UInt8Ptr_frompointer(t)

# Register UInt8Ptr in _dap:
_dap.UInt8Ptr_swigregister(UInt8Ptr)
class Equatable(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def equals(self, a, b):
        return _dap.Equatable_equals(self, a, b)
    __swig_destroy__ = _dap.delete_Equatable

    def __init__(self):
        if self.__class__ == Equatable:
            _self = None
        else:
            _self = self
        _dap.Equatable_swiginit(self, _dap.new_Equatable(_self, ))
    def __disown__(self):
        self.this.disown()
        _dap.disown_Equatable(self)
        return weakref.proxy(self)

# Register Equatable in _dap:
_dap.Equatable_swigregister(Equatable)
class StateChangeListener(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def on_state_change(self, state):
        return _dap.StateChangeListener_on_state_change(self, state)
    __swig_destroy__ = _dap.delete_StateChangeListener

    def __init__(self):
        if self.__class__ == StateChangeListener:
            _self = None
        else:
            _self = self
        _dap.StateChangeListener_swiginit(self, _dap.new_StateChangeListener(_self, ))
    def __disown__(self):
        self.this.disown()
        _dap.disown_StateChangeListener(self)
        return weakref.proxy(self)

# Register StateChangeListener in _dap:
_dap.StateChangeListener_swigregister(StateChangeListener)
class UInt8Array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _dap.UInt8Array_swiginit(self, _dap.new_UInt8Array(nelements))
    __swig_destroy__ = _dap.delete_UInt8Array

    def __getitem__(self, index):
        return _dap.UInt8Array___getitem__(self, index)

    def __setitem__(self, index, value):
        return _dap.UInt8Array___setitem__(self, index, value)

    def cast(self):
        return _dap.UInt8Array_cast(self)

    @staticmethod
    def frompointer(t):
        return _dap.UInt8Array_frompointer(t)

    def data(self):
        return _dap.UInt8Array_data(self)

# Register UInt8Array in _dap:
_dap.UInt8Array_swigregister(UInt8Array)
class RawData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def to_bytes(self):
        return _dap.RawData_to_bytes(self)
    data = property(_dap.RawData_data_get, _dap.RawData_data_set)
    size = property(_dap.RawData_size_get, _dap.RawData_size_set)

    def __init__(self):
        _dap.RawData_swiginit(self, _dap.new_RawData())
    __swig_destroy__ = _dap.delete_RawData

# Register RawData in _dap:
_dap.RawData_swigregister(RawData)

def pack(data):
    return _dap.pack(data)
class MSet_Token(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    elements = property(_dap.MSet_Token_elements_get, _dap.MSet_Token_elements_set)
    size = property(_dap.MSet_Token_size_get, _dap.MSet_Token_size_set)

    def __init__(self):
        _dap.MSet_Token_swiginit(self, _dap.new_MSet_Token())
    __swig_destroy__ = _dap.delete_MSet_Token

# Register MSet_Token in _dap:
_dap.MSet_Token_swigregister(MSet_Token)

def MSet_Token_of(elements):
    return _dap.MSet_Token_of(elements)

def MSet_Token_get(set, index):
    return _dap.MSet_Token_get(set, index)

def MSet_Token_free(set):
    return _dap.MSet_Token_free(set)
class DAPState(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    tokens = property(_dap.DAPState_tokens_get, _dap.DAPState_tokens_set)
    msg = property(_dap.DAPState_msg_get, _dap.DAPState_msg_set)

    def __init__(self):
        _dap.DAPState_swiginit(self, _dap.new_DAPState())
    __swig_destroy__ = _dap.delete_DAPState

# Register DAPState in _dap:
_dap.DAPState_swigregister(DAPState)
class Rule(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    preconditions = property(_dap.Rule_preconditions_get, _dap.Rule_preconditions_set)
    rate = property(_dap.Rule_rate_get, _dap.Rule_rate_set)
    effects = property(_dap.Rule_effects_get, _dap.Rule_effects_set)
    msg = property(_dap.Rule_msg_get, _dap.Rule_msg_set)

    def __init__(self):
        _dap.Rule_swiginit(self, _dap.new_Rule())
    __swig_destroy__ = _dap.delete_Rule

# Register Rule in _dap:
_dap.Rule_swigregister(Rule)
class Neighbour(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_dap.Neighbour_name_get, _dap.Neighbour_name_set)

    def __init__(self):
        _dap.Neighbour_swiginit(self, _dap.new_Neighbour())
    __swig_destroy__ = _dap.delete_Neighbour

# Register Neighbour in _dap:
_dap.Neighbour_swigregister(Neighbour)

def launch_simulation(rules, s0, port, neighbors, on_state_change, equals_fn):
    return _dap.launch_simulation(rules, s0, port, neighbors, on_state_change, equals_fn)

def launch_simulation_wrapper(rules, s0, port, neighbors, listener, equatable):
    return _dap.launch_simulation_wrapper(rules, s0, port, neighbors, listener, equatable)

